
package sd.tp1.client.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ContentServerService", targetNamespace = "http://server.tp1.sd/", wsdlLocation = "http://192.168.1.3:8081/serverproxy?wsdl")
public class ContentServerService
    extends Service
{

    private final static URL CONTENTSERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONTENTSERVERSERVICE_EXCEPTION;
    private final static QName CONTENTSERVERSERVICE_QNAME = new QName("http://server.tp1.sd/", "ContentServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.1.3:8081/serverproxy?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONTENTSERVERSERVICE_WSDL_LOCATION = url;
        CONTENTSERVERSERVICE_EXCEPTION = e;
    }

    public ContentServerService() {
        super(__getWsdlLocation(), CONTENTSERVERSERVICE_QNAME);
    }

    public ContentServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONTENTSERVERSERVICE_QNAME, features);
    }

    public ContentServerService(URL wsdlLocation) {
        super(wsdlLocation, CONTENTSERVERSERVICE_QNAME);
    }

    public ContentServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONTENTSERVERSERVICE_QNAME, features);
    }

    public ContentServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ContentServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ContentServer
     */
    @WebEndpoint(name = "ContentServerPort")
    public ContentServer getContentServerPort() {
        return super.getPort(new QName("http://server.tp1.sd/", "ContentServerPort"), ContentServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ContentServer
     */
    @WebEndpoint(name = "ContentServerPort")
    public ContentServer getContentServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.tp1.sd/", "ContentServerPort"), ContentServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONTENTSERVERSERVICE_EXCEPTION!= null) {
            throw CONTENTSERVERSERVICE_EXCEPTION;
        }
        return CONTENTSERVERSERVICE_WSDL_LOCATION;
    }

}
