
package sd.tp1.client.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSServerService", targetNamespace = "http://server.tp1.sd/", wsdlLocation = "http://192.168.1.3:8081/serverws?wsdl")
public class WSServerService
    extends Service
{

    private final static URL WSSERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSSERVERSERVICE_EXCEPTION;
    private final static QName WSSERVERSERVICE_QNAME = new QName("http://server.tp1.sd/", "WSServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.1.3:8081/serverws?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSSERVERSERVICE_WSDL_LOCATION = url;
        WSSERVERSERVICE_EXCEPTION = e;
    }

    public WSServerService() {
        super(__getWsdlLocation(), WSSERVERSERVICE_QNAME);
    }

    public WSServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSSERVERSERVICE_QNAME, features);
    }

    public WSServerService(URL wsdlLocation) {
        super(wsdlLocation, WSSERVERSERVICE_QNAME);
    }

    public WSServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSSERVERSERVICE_QNAME, features);
    }

    public WSServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSServer
     */
    @WebEndpoint(name = "WSServerPort")
    public WSServer getWSServerPort() {
        return super.getPort(new QName("http://server.tp1.sd/", "WSServerPort"), WSServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSServer
     */
    @WebEndpoint(name = "WSServerPort")
    public WSServer getWSServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.tp1.sd/", "WSServerPort"), WSServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSSERVERSERVICE_EXCEPTION!= null) {
            throw WSSERVERSERVICE_EXCEPTION;
        }
        return WSSERVERSERVICE_WSDL_LOCATION;
    }

}
